#!/usr/bin/env node
// setup_scripts.js — 一次性工具：解析 Script PDF → 生成 src/script_data.js
//
// 用法：node setup_scripts.js "./PW3E L4 RW Script.pdf"
// 运行一次后，script 数据永久内嵌，服务器自动按 Unit 匹配。

const pdfParse  = require('pdf-parse');
const PDFParser = require('pdf2json');
const fs        = require('fs');
const path      = require('path');

async function extractText(buffer) {
  try {
    const d = await pdfParse(buffer);
    if (d.text.trim().length > 100) return d.text;
  } catch(_) {}
  return new Promise((res, rej) => {
    const p = new PDFParser(null, 1);
    p.on('pdfParser_dataReady', () =>
      res((p.getRawTextContent()||'').replace(/---+Page[^-]+-+/g,'\n')));
    p.on('pdfParser_dataError', rej);
    p.parseBuffer(buffer);
  });
}

function splitByUnit(text) {
  // Match: UNIT 1: TITLE / Unit 1: Title
  const rx = /(?:^|\n)(UNIT\s*(\d+)\s*:[^\n]*)/gi;
  const sections = [];
  let m, lastIdx = 0, lastUnit = null, lastMarker = '';

  while ((m = rx.exec(text)) !== null) {
    if (lastUnit !== null) {
      const content = text.slice(lastIdx, m.index).trim();
      if (content.length > 50) sections.push({ unit: lastUnit, marker: lastMarker, content });
    }
    lastUnit   = parseInt(m[2]);
    lastMarker = m[1].trim();
    lastIdx    = m.index + m[0].length;
  }
  if (lastUnit !== null) {
    const content = text.slice(lastIdx).trim();
    if (content.length > 50) sections.push({ unit: lastUnit, marker: lastMarker, content });
  }
  return sections;
}

async function main() {
  const pdfPath = process.argv[2];
  if (!pdfPath) {
    console.log('用法：node setup_scripts.js <script.pdf>');
    console.log('示例：node setup_scripts.js "./PW3E L4 Video Scripts.pdf"');
    process.exit(1);
  }
  if (!fs.existsSync(pdfPath)) {
    console.error(`❌  找不到文件：${pdfPath}`);
    process.exit(1);
  }

  console.log(`\n📜  读取：${path.basename(pdfPath)}`);
  const buffer = fs.readFileSync(pdfPath);

  process.stdout.write('📄  提取文字... ');
  const text = await extractText(buffer);
  console.log(`完成（${text.length} 字符）`);

  const sections = splitByUnit(text);
  if (!sections.length) {
    console.error('❌  未找到 "UNIT X:" 标记，请确认 PDF 格式。');
    console.log('\n文字预览：\n' + text.slice(0, 400));
    process.exit(1);
  }

  console.log(`\n✅  识别到 ${sections.length} 个 Unit 脚本：`);
  sections.forEach(s => console.log(`   Unit ${s.unit}: ${s.content.length} 字符`));

  // Build JS module content
  const lines = ['// src/script_data.js'];
  lines.push(`// Auto-generated by setup_scripts.js from: ${path.basename(pdfPath)}`);
  lines.push(`// Run "node setup_scripts.js <pdf>" to regenerate.\n`);
  lines.push('const UNIT_SCRIPTS = {');
  sections.forEach(s => {
    const escaped = s.content.replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\${/g,'\\${');
    lines.push(`  ${s.unit}: \`${escaped}\`,`);
  });
  lines.push('};\n');
  lines.push('module.exports = { UNIT_SCRIPTS };');

  const outPath = path.join(__dirname, 'src', 'script_data.js');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

  console.log(`\n🎉  已生成：src/script_data.js`);
  console.log('    服务器重启后自动生效，无需再上传 Script PDF。');
  console.log('\n重启命令：pm2 restart server\n');
}

main().catch(e => { console.error('❌', e.message); process.exit(1); });
